name: 015_LabelGenerator
run-name: 015_LabelGenerator
on:
  workflow_dispatch:
    inputs:
      label:
        description: "Label"
        required: true
        type: string
      description:
        description: "Description"
        required: true
        type: string
      color:
        description: "Color"
        required: true
        type: string

# Sets permissions for the entire workflow
permissions:
  contents: write

jobs:
  determine_env:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Determine env"
      - id: set_env
        run: echo "::set-output name=deploy_env::"${{ github.ref_name }}""
    outputs:
      deploy_env: ${{ steps.set_env.outputs.deploy_env }}

  create-firefighter-user:
    needs: determine_env
    runs-on: ubuntu-latest
    environment: ${{ needs.determine_env.outputs.deploy_env}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          token: ${{ github.token }}

      - name: Label Inputs
        env:
          LABEL: ${{ inputs.label }}
          DESCRIPTION: ${{ vars.ENV_VALUE }}
          COLOR: ${{ inputs.color }}
          GH_TOKEN: ${{ secrets.OWN_GITHUB_TOKEN_TST }}

        run: |
          gh label create "$LABEL" --description "$DESCRIPTION" --color "$COLOR" --force
