name: 015_LabelGeneratorDev
run-name: 015_LabelGeneratorDev
on:
  workflow_dispatch:
    inputs:
      label:
        description: "Label"
        required: true
        type: string
      description:
        description: "Description"
        required: true
        type: string
      color:
        description: "Color"
        required: true
        type: string

# Sets permissions for the entire workflow
permissions:
  contents: write

jobs:
  create-firefighter-user:
    runs-on: ubuntu-latest
    environment: pro

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          token: ${{ github.token }}

      - name: my-step
        run: |
          echo "Hello World!"
          ACTOR="${{ github.actor }}"
          EVENT_NAME="${{ github.event_name }}"
          COMMIT_SHA="${{ github.sha }}"
          BRANCH_OR_TAG_REF="${{ github.ref }}"
          REPOSITORY="${{ github.repository }}"
          WORKFLOW_NAME="${{ github.workflow }}"
          RUN_ID="${{ github.run_id }}"
          RUN_NUMBER="${{ github.run_number }}"
          JOB="${{ github.job }}"

          echo "| **Concept**            | **Value**                    |"
          echo "|------------------------|------------------------------|"
          echo "| **Actor**              | ${ACTOR}                     |"
          echo "| **Event Name**         | ${EVENT_NAME}                |"
          echo "| **Commit SHA**         | ${COMMIT_SHA}                |"
          echo "| **Branch or Tag Ref**  | ${BRANCH_OR_TAG_REF}         |"
          echo "| **Repository**         | ${REPOSITORY}                |"
          echo "| **Workflow Name**      | ${WORKFLOW_NAME}             |"
          echo "| **Run ID**             | ${RUN_ID}                    |"
          echo "| **Run Number**         | ${RUN_NUMBER}                |"
          echo "| **Job**                | ${JOB}                       |"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Label Inputs
        env:
          LABEL: ${{ inputs.label }}
          DESCRIPTION: ${{ vars.ENV_VALUE }}
          COLOR: ${{ inputs.color }}
          GH_TOKEN: ${{ secrets.OWN_GITHUB_TOKEN_TST }}

        run: |
          gh label create "$LABEL" --description "$DESCRIPTION" --color "$COLOR" --force
