name: sh_v4
run-name: sh_v4

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action to perform"
        required: true
        default: "list"
        type: choice
        options:
          - list-envs
          - list-vars
          - create-envs
          - create-vars
      organization:
        description: "Organization name"
        required: true
        type: string
      repository:
        description: "Repository name (optional for variable creation operations)"
        required: false
        type: string
      filename:
        description: "FileName (optional for list operations)"
        required: false
        type: string

jobs:
  manage-environments:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      - name: Install gh-environments extension
        run: |
          gh extension install katiem0/gh-environments
          echo "Extension installed successfully"
        env:
          GH_TOKEN: ${{ secrets.OWN_GITHUB_TOKEN_TST }}

      - name: List existing environments
        if: ${{ inputs.action == 'list-envs' }}
        run: |
          echo "Listing environments for organization: ${{ inputs.organization }}"
          gh environments list ${{ inputs.organization }} ${{ inputs.repository }} --output-file verification-report.csv
        env:
          GH_TOKEN: ${{ secrets.OWN_GITHUB_TOKEN_TST }}

      - name: List existing environments
        if: ${{ inputs.action == 'list-vars' }}
        run: |
          echo "Listing environments for organization: ${{ inputs.organization }}"
          gh environments variables list ${{ inputs.organization }} ${{ inputs.repository }} --output-file verification-variables-report.csv
        env:
          GH_TOKEN: ${{ secrets.OWN_GITHUB_TOKEN_TST }}

      - name: Create environment
        if: ${{ inputs.action == 'create-envs' }}
        run: |
          echo "Create environments for organization: ${{ inputs.organization }}"
          gh environments create ${{ inputs.organization }}/${{ inputs.repository }} --from-file .\${{ inputs.filename }}
        env:
          GH_TOKEN: ${{ secrets.OWN_GITHUB_TOKEN_TST }}

      - name: Create environment variables
        if: ${{ inputs.action == 'create-vars' }}
        run: |
          echo "Create environments variables for organization: ${{ inputs.organization }}"
          gh environments variables create ${{ inputs.organization }} --from-file .\${{ inputs.filename }}

        env:
          GH_TOKEN: ${{ secrets.OWN_GITHUB_TOKEN_TST }}
      - name: Upload reports as artifacts
        if: ${{ inputs.action == 'list-envs' || inputs.action == 'list-vars' }}
        uses: actions/upload-artifact@v4
        with:
          name: environment-reports
          path: |
            *.csv
